// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04-ftGvhiTE9_PUOWt2t9V1pVeiR4mdY',
    appId: '1:177178853396:web:9b01fb653396434a0ea701',
    messagingSenderId: '177178853396',
    projectId: 'mobileapp-ba8ce',
    authDomain: 'mobileapp-ba8ce.firebaseapp.com',
    databaseURL: 'https://mobileapp-ba8ce-default-rtdb.firebaseio.com',
    storageBucket: 'mobileapp-ba8ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGAqVU920rsKxvj8nWBHrZEg2V3z934o',
    appId: '1:177178853396:android:d1beab7719b523fe0ea701',
    messagingSenderId: '177178853396',
    projectId: 'mobileapp-ba8ce',
    databaseURL: 'https://mobileapp-ba8ce-default-rtdb.firebaseio.com',
    storageBucket: 'mobileapp-ba8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinttCmjcF5VPFJHaM0baEycmaX0LSG_k',
    appId: '1:177178853396:ios:b8102ba56c7a5a3a0ea701',
    messagingSenderId: '177178853396',
    projectId: 'mobileapp-ba8ce',
    databaseURL: 'https://mobileapp-ba8ce-default-rtdb.firebaseio.com',
    storageBucket: 'mobileapp-ba8ce.appspot.com',
    iosBundleId: 'com.example.mobileErasmus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinttCmjcF5VPFJHaM0baEycmaX0LSG_k',
    appId: '1:177178853396:ios:3ab31167eb197cde0ea701',
    messagingSenderId: '177178853396',
    projectId: 'mobileapp-ba8ce',
    databaseURL: 'https://mobileapp-ba8ce-default-rtdb.firebaseio.com',
    storageBucket: 'mobileapp-ba8ce.appspot.com',
    iosBundleId: 'com.example.mobileErasmus.RunnerTests',
  );
}
